### ISSUE TITLE
What types of objects can be cached?

### ISSUE THREAD

**Issue by stevesimmons** [deliro/moka-py#1]
Thanks for this project!

As the title asks, what types of objects can be cached? Does `moka` support any Python object? Or only ones that can be serialized/deserialized in some way? 

Could you please add something to the README explaining this?

**Comment by deliro** [comment]
Hi! As @alwavshumilin said, `key` must be `Hashable` and `value` can be arbitrary Python object. moka-py doesn't serialize or deserialize values, it stores their references instead.

Thank you for the question! I'll update docs to clarify this
